version: 1.{build}

environment:
  matrix:
    - VisualStudio: 14.0
      VisualStudioGenerator: "14 2015"
      ConfigurationPlatform: "Win32"
      configuration: "Debug"
      vcvarsall_platform: "x86"
      PlatformToolset: "v140"
    - VisualStudio: 14.0
      VisualStudioGenerator: "14 2015"
      ConfigurationPlatform: "x64"
      configuration: "Debug"
      vcvarsall_platform: "x64"
      PlatformToolset: "v140"
    - VisualStudio: 2017
      VisualStudioGenerator: "15 2017"
      ConfigurationPlatform: "Win32"
      configuration: "Debug"
      vcvarsall_platform: "x86"
      PlatformToolset: "v141"
    - VisualStudio: 2017
      VisualStudioGenerator: "15 2017"
      ConfigurationPlatform: "x64"
      configuration: "Debug"
      vcvarsall_platform: "x64"
      PlatformToolset: "v141"
    - VisualStudio: 2019
      VisualStudioGenerator: "16 2019"
      ConfigurationPlatform: "Win32"
      configuration: "Debug"
      vcvarsall_platform: "x86"
      PlatformToolset: "v142"
    - VisualStudio: 2019
      VisualStudioGenerator: "16 2019"
      ConfigurationPlatform: "x64"
      configuration: "Debug"
      vcvarsall_platform: "x64"
      PlatformToolset: "v142"

build_script:
  - ECHO Building %configuration% %platform% with MSVC %VisualStudio% (Visual Studio %VisualStudioGenerator%) using %PlatformToolset% PlatformToolset
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudio%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - cmake -DCMAKE_COMPILE_WARNING_AS_ERROR=On -G "Visual Studio %VisualStudioGenerator%" -A %ConfigurationPlatform% .
  - set _CL_=/WX
  - msbuild "simplecpp.sln" /consoleloggerparameters:Verbosity=minimal /target:Build /property:Configuration="%configuration%";Platform=%ConfigurationPlatform% /p:PlatformToolset=%PlatformToolset% /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - debug\testrunner.exe
  - debug\simplecpp.exe simplecpp.cpp -e
