version: 1.{build}

environment:
  matrix:
    - VisualStudioVersion: 14.0
      platform: "Win32"
      configuration: "Debug"
      vcvarsall_platform: "x86"
      PlatformToolset: "v140"

build_script:
  - ECHO Building %configuration% %platform% with MSVC %VisualStudioVersion% using %PlatformToolset% PlatformToolset
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - cmake -DCMAKE_COMPILE_WARNING_AS_ERROR=On -G "Visual Studio 14" .
  - dir
  - set _CL_=/WX
  - msbuild "simplecpp.sln" /consoleloggerparameters:Verbosity=minimal /target:Build /property:Configuration="%configuration%";Platform=%platform% /p:PlatformToolset=%PlatformToolset% /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - debug\testrunner.exe
  - debug\simplecpp.exe simplecpp.cpp -e
