#!/bin/bash
# The version check in this script is used to avoid commit battles
# between different developers that use different astyle versions as
# different versions might have different output (this has happened in
# the past).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd $SCRIPT_DIR

# If project management wishes to take a newer astyle version into use
# just change this string to match the start of astyle version string.
ASTYLE_VERSION="Artistic Style Version 3.0.1"
ASTYLE="astyle"

DETECTED_VERSION=`$ASTYLE --version 2>&1`
if [[ "$DETECTED_VERSION" != ${ASTYLE_VERSION}* ]]; then
    echo "You should use: ${ASTYLE_VERSION}";
    echo "Detected: ${DETECTED_VERSION}"
    exit 1;
fi

$ASTYLE --options="$SCRIPT_DIR/.astylerc" *.cpp
$ASTYLE --options="$SCRIPT_DIR/.astylerc" *.h
