# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: clang-tidy

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      # the man-db trigger causes package installations to stall for several minutes at times. so just drop the package.
      # see https://github.com/actions/runner/issues/4030
      - name: Remove man-db package
        run: |
          sudo apt-get update
          sudo apt-get remove man-db

      - name: Install missing software
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make

      - name: Install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 23
          sudo apt-get install clang-tidy-23

      - name: Verify clang-tidy configuration
        run: |
          clang-tidy-23 --verify-config

      - name: Prepare CMake (C++11)
        run: |
          cmake -S . -B cmake.output.cxx11 -Werror=dev --warn-uninitialized -DCMAKE_CXX_STANDARD=11 -DCMAKE_COMPILE_WARNING_AS_ERROR=On -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CXX: clang-23

      - name: Clang-Tidy (C++11)
        run: |
          run-clang-tidy-23 -q -j $(nproc) -enable-check-profile -p=cmake.output.cxx11

      - name: Prepare CMake (C++14)
        run: |
          cmake -S . -B cmake.output.cxx14 -Werror=dev --warn-uninitialized -DCMAKE_CXX_STANDARD=14 -DCMAKE_COMPILE_WARNING_AS_ERROR=On -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CXX: clang-23

      - name: Clang-Tidy (C++14)
        run: |
          run-clang-tidy-23 -q -j $(nproc) -enable-check-profile -p=cmake.output.cxx14

      - name: Prepare CMake (C++17)
        run: |
          cmake -S . -B cmake.output.cxx17 -Werror=dev --warn-uninitialized -DCMAKE_CXX_STANDARD=17 -DCMAKE_COMPILE_WARNING_AS_ERROR=On -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CXX: clang-23

      - name: Clang-Tidy (C++17)
        run: |
          run-clang-tidy-23 -q -j $(nproc) -enable-check-profile -p=cmake.output.cxx17

      - name: Prepare CMake (C++20)
        run: |
          cmake -S . -B cmake.output.cxx20 -Werror=dev --warn-uninitialized -DCMAKE_CXX_STANDARD=20 -DCMAKE_COMPILE_WARNING_AS_ERROR=On -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CXX: clang-23

      - name: Clang-Tidy (C++20)
        run: |
          run-clang-tidy-23 -q -j $(nproc) -enable-check-profile -p=cmake.output.cxx20

      - name: Prepare CMake (C++23)
        run: |
          cmake -S . -B cmake.output.cxx23 -Werror=dev --warn-uninitialized -DCMAKE_CXX_STANDARD=23 -DCMAKE_COMPILE_WARNING_AS_ERROR=On -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CXX: clang-23

      - name: Clang-Tidy (C++23)
        run: |
          run-clang-tidy-23 -q -j $(nproc) -enable-check-profile -p=cmake.output.cxx23

      - name: Prepare CMake (C++26)
        run: |
          cmake -S . -B cmake.output.cxx26 -Werror=dev --warn-uninitialized -DCMAKE_CXX_STANDARD=26 -DCMAKE_COMPILE_WARNING_AS_ERROR=On -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CXX: clang-23

      - name: Clang-Tidy (C++26)
        run: |
          run-clang-tidy-23 -q -j $(nproc) -enable-check-profile -p=cmake.output.cxx26
