# the purpose of this github action is to test that simplecpp source code can be compiled using old gcc versions.
# the gcc images we use here are copied from the official gcc images on docker hub

name: gcc-versions

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        #image: ["ghcr.io/cppcheck-opensource/gcc:5.4", "ghcr.io/cppcheck-opensource/gcc:6.5", "ghcr.io/cppcheck-opensource/gcc:7.5", "ghcr.io/cppcheck-opensource/gcc:8.5", "ghcr.io/cppcheck-opensource/gcc:9.5"]
        image: ["ghcr.io/cppcheck-opensource/gcc:5.4"]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build and run tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/simplecpp -w /simplecpp ${{ matrix.image }} make -j$(nproc) simplecpp testrunner
          docker run --rm -v ${{ github.workspace }}:/simplecpp -w /simplecpp ${{ matrix.image }} ./testrunner
